--if we have 45 + 5 + 2 + 1 , then we call the numbers "operands" and the addictive symbol "operator"
--python can do different math operations ( + , - , * , /) and so on.. , "//" is for integer division ex: 25//6 = 4
